### PR TITLE
Add support for XZ deb files compression

### PR DESCRIPTION
**Pull request by ThorAsgardDev**
Some deb files use XZ compression instead of gzip. This pull request allows to handle these files.

### CODE REVIEW

**Review by ctron — APPROVED** [review]

**Comment by ThorAsgardDev** [comment]
Hello,
Do you plan to create a new release including this PR ?

**Comment by ctron** [comment]
Sure I can do that. I had to update a few dependencies as the build didn't like newer Java versions :)

It would be great if you could do a test from `master`, and let me know if it works. If that's the case, I push out a new release (`0.0.3`) to Maven central.

**Comment by ThorAsgardDev** [comment]
Hello @ctron,
I just tested the master and it works.
By the way, could you also release the rpm-builder when my PR will be merged ?

**Comment by ctron** [comment]
Thanks! I just released this as `0.0.3`, it might take a bit until it can be seen at Maven Central.

I had to make a few more changes in the POM in order to get it compiled with Java 11, it should still work on Java 8! If that is not the case, or if my changes broke something, just let me know and I will take a look!

I will go ahead and release the `rpm-builder` next, that should be much simpler :)

**Pull request merged**
